name: build.yml
on:
  workflow_dispatch:
  schedule:
    - cron: "30 3,9,15,21 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

          echo "GEOIP_URL=https://raw.githubusercontent.com/runetfreedom/russia-blocked-geoip/release/geoip.dat" >> $GITHUB_ENV
          echo "GEOSITE_URL=https://raw.githubusercontent.com/runetfreedom/russia-blocked-geosite/release/geosite.dat" >> $GITHUB_ENV
        shell: bash

      - name: Download geodata
        run: |
          mkdir -p ./publish
          curl -sSL $GEOIP_URL > ./full-geoip.dat
          curl -sSL $GEOSITE_URL > ./full-geosite.dat

      - name: Filter geosite.dat
        run: |
          python3 tools/filter-geosite.py ./full-geosite.dat ./publish/geosite.dat
          cd ./publish && sha256sum geosite.dat > geosite.dat.sha256sum

      - name: Filter geoip.dat
        run: |
          python3 tools/filter-geoip.py ./full-geoip.dat ./publish/geoip.dat
          cd ./publish && sha256sum geoip.dat > geoip.dat.sha256sum

      - name: Generate category lists
        run: |
          python3 tools/extract-categories.py geosite ./publish/geosite.dat ./publish/geosite_categories.txt
          python3 tools/extract-categories.py geoip ./publish/geoip.dat ./publish/geoip_categories.txt

      - name: Release and upload assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: ${{ env.RELEASE_NAME }}
          tag: ${{ env.TAG_NAME }}
          file_glob: true
          file: ./publish/*

      - name: Git push assets to "release" branch
        run: |
          cd publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "$RELEASE_NAME"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release
